### ISSUE TITLE
🎨 CLUB

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/samenvvv#220]
### Describe the feature you'd like to request

We would like to have a club page on which any authenticated user can post his/her arts. The page will look like this social media project https://github.com/adrianhajdin/project_shareme_social_media.

This feature has three parts and some parts will probably be created in separated branches/issues/PRs.

1. Backend data modeling
2. Frontend
3. Authentication

## 1. Backend

Extend art and artist models.

## 2. Frontend

- [ ] List arts in `/club` page
  - [ ] Add masonry grid #221 
  - [ ] Add filtering by category feature in sidebar #222 
  - [ ] Add pagination #223 
- [ ] Create SSG/ISR single art page `/club/art/:id` 
  - [ ] Show details (description or story) of the art #224 
  - [ ] Add `Like` button #225 
  - [ ] Add comment feature #226 
- [ ] Create SSG/ISR singe artist page `/club/artist/:username`
  - [ ] Show details of the artist #227 
  - [ ] List the artist's arts #228 

## 3. Authentication

Authentication is actually not specific for this feature. We will be using login/signup for also **Application for Competitions**.

> TODO: Explain steps

### Describe the solution you'd like

> TODO: Describe
